### ISSUE TITLE
X-Frame-Police Options on /community/calendar

### ISSUE THREAD

**Issue by phumberdroz** [cncf/wordpress-site#158] opened 2019-12-11 21:29 UTC
Please see attached Picture
<img width="914" alt="Screenshot 2019-12-11 at 22 24 51" src="https://user-images.githubusercontent.com/3389721/70661992-ad1f3680-1c65-11ea-8b37-d9545ebf78e1.png">

https://www.cncf.io/community/calendar/

Firefox Version Info:
72.0b5
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:72.0) Gecko/20100101 Firefox/72.0

**Comment by dankohn** [comment] 2019-12-12 00:39
Super helpful report, thanks. I'm not seeing it on Chrome but we'll look into correcting.

**Comment by cjyabraham** [comment] 2019-12-12 09:07
I'm not able to reproduce on Firefox 71.0 or 72.0b1 on macOS 10.15.  Perhaps this is a FF bug introduced between 72.0b1 and b5?  [This looks like the issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1593321) but looks like they have fixed it.  Perhaps it'll be released in a later beta.

Closing since it looks like there's nothing for us to do on cncf.io.

**Closed by cjyabraham** 2019-12-12 09:07 UTC
Labels: bug
