### ISSUE TITLE
Site slow (October 11)

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#124] opened 2019-10-11 14:11 UTC
I'm experiencing significant slowdown on cncf.io, specifically on the Speakers Bureau page. 5 seconds to load a page.

**Comment by cjyabraham** [comment] 2019-10-11 15:52
I don't believe the site has slowed down at all.  What makes you think it is slower @KimMcMahon .

The cncf.io site is very slow, in general, due to the way it is built.  We are planning on addressing this during the rebuild.  I don't think it's worth putting much more effort than we already have done to speed up the current site.

@deigolocco if there's any way to make the Speaker's Bureau filters faster, then that might be something to look at but I wouldn't waste too much time on this as we'll be overhauling everything in the future anyway.

**Comment by cjyabraham** [comment] 2019-10-11 15:53
One other thing to add, @KimMcMahon if you are logged in to the admin, the site will be significantly slower than if you are not.  That's because you are not getting a cached version.  This is by design.  The general public, however, will be experiencing the cached version which is faster.

**Comment by KimMcMahon** [comment] 2019-10-11 15:54
Thanks @cjyabraham. Yes, I'm logged in. I'll close this.

**Comment by dankohn** [comment] 2019-10-11 16:15
I'm not logged in but when I go to https://www.cncf.io/speakers/?languages=Bengali&_lc=languages and click reset it takes over 10 seconds to load the page of 81 speakers. I'd like you and @deigolocco to look at why. I suspect https://www.cncf.io/speakers/ is not being cached.

**Comment by deigolocco** [comment] 2019-10-11 16:51
@dankohn the way that Ultimate Members saves the information in metas as serialized arrays
![Captura de tela de 2019-10-11 11-14-37](https://user-images.githubusercontent.com/5631313/66661038-a865e400-ec1c-11e9-83f1-485d9061890f.png)
Makes the queries that we need to run complex and slow, especially because the filters interact with each other.
We are working to improve the cache of these queries using [Wordpress Transient API](https://codex.wordpress.org/Transients_API)

**Comment by cjyabraham** [comment] 2019-10-12 04:01
@deigolocco using transients sounds like a good idea.  I'd be interested to see how you do that.

Additionally, I took a quick look at the ajax requests made by the filters.  None of them are being cached by Pantheon as each request is sent with these headers: `cache-control: no-cache, must-revalidate, max-age=0`.  I think this is because you are calling `wp-admin/admin-ajax.php` which is never cached since it's part of the admin.

I've read that you can do AJAX using [rewrite rules](https://codex.wordpress.org/Rewrite_API).  See the "AJAX Endpoints" section part-way down on [this page](https://10up.github.io/Engineering-Best-Practices/php/#performance).  Then we can cache the results of each AJAX call (i.e. each filter combination).  Obviously there are a lot of different possible filter combinations so I'm not sure what the cache coverage would be but at least the common combinations would get cached.  Do you think this would help?

**Comment by deigolocco** [comment] 2019-10-15 21:26
@cjyabraham https://fz-124-cncf.pantheonsite.io/speakers/

The implementation was made using the WordPress Transient API, and for each query executed on the page, a hash of the arguments is generated and this hash is used as the transient key.
​
Ex:
```php
<?php
​
$args = array(
    'fields'     => 'ID',
    'number'     => $per_page,
    'meta_key'   => 'last_name',
    'order'      => 'asc',
    'orderby'    => 'meta_value',
    'paged'      => 1,
    'role__in'   => array( 'um_speaker' ),
);
```
​
The hash generated will be: *fuerza_speakers_92b28d7f74b0c944452e139d4d785644*

Therefore, in the next query with these same arguments, the application will search directly from the transient. Decreasing response time considerably.
​
We also did the call substitution of `wp-admin/admin-ajax.php` for a custom route using the WP REST API (`wp-json/fuerza/v1/speakers`).
​
Besides reducing the response time, this is more performative, it also generates the possibility of being cached by Pantheon.

I'de like to enforce that we still have slow queries, so the first hit will be slow, after it the cache will work. On the website rebuilt this is a very important point.

Tomorrow we'll work in the cache invalidations improvement. Now it's keeping the cache for 30min, but the plan is invalidate the cache each time a speaker has an update.

**Comment by deigolocco** [comment] 2019-10-17 13:43
hi guys, could you check the performance now? https://fz-124-cncf.pantheonsite.io/speakers/

**Comment by KimMcMahon** [comment] 2019-10-17 14:57
@deigolocco Its faster. Still about 5 seconds to load the filter when I filter on a project.

**Comment by deigolocco** [comment] 2019-10-17 16:52
@KimMcMahon could you send the url of the slow filtering please?

**Comment by KimMcMahon** [comment] 2019-10-17 16:56
@deigolocco https://fz-124-cncf.pantheonsite.io/speakers/?cncf_expertise=Kubernetes&_lc=cncf_expertise

**Comment by deigolocco** [comment] 2019-10-17 17:01
@KimMcMahon for me is taking less than one sec, please reset your filtering and try again

**Comment by KimMcMahon** [comment] 2019-10-17 19:50
Tested - timing is quick now. Thank you!

**Comment by deigolocco** [comment] 2019-10-18 12:23
adjusted and merged @cjyabraham, you can deploy

**Comment by cjyabraham** [comment] 2019-10-19 09:48
When you pick an expertise and a project at the same time, the server times out.  [Try this for example](https://fz-124-cncf.pantheonsite.io/speakers/?expertise=Community&_project=CloudEvents&_lc=expertise).  Does it work for you?

Also, [other queries](https://fz-124-cncf.pantheonsite.io/speakers/?languages=Chinese&_lc=languages) [don't seem to work either](https://fz-124-cncf.pantheonsite.io/speakers/?sb_certifications=CKA&_lc=sb_certifications).

**Comment by cjyabraham** [comment] 2019-10-20 05:06
Hmm.  They seem to be working today.  Did anything change?

**Comment by deigolocco** [comment] 2019-10-21 11:19
@cjyabraham yes. When we merged issue 125 with 124 the cache was clear. We are pre-caching all itens for each filter, but their combinations are being cached on demand.
Was necessary to run these commands at server on database:
```
OPTIMIZE TABLE wp_usermeta 
OPTIMIZE TABLE wp_users 
OPTIMIZE TABLE wp_options
```

**Comment by cjyabraham** [comment] 2019-10-21 13:15
deployed

**Closed by cjyabraham** 2019-10-21 13:15 UTC
Labels: bug
